SistemaVenta.AplicacionWeb/Controllers/ChatController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using SistemaVenta.AplicacionWeb.Utilidades.SignalR;

namespace SistemaVenta.AplicacionWeb.Controllers
{
    public class ChatController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        private readonly IHubContext<ChatHub> _hubContext;

        public ChatController(IHubContext<ChatHub> hubContext)
        {
            _hubContext = hubContext;
        }


        [HttpPost]
        public IActionResult EnviarMensaje(string mensaje)
        {
            // Procesar el mensaje, almacenarlo en la base de datos, realizar alguna lógica, etc.

            // Enviar el mensaje a todos los clientes a través del hub SignalR
            _hubContext.Clients.All.SendAsync("ReceiveMessage", new { text = mensaje });

            // Puedes devolver algo, por ejemplo, un código de estado o un mensaje de éxito
            return Ok("Mensaje enviado con éxito");
        }
    }
}

SistemaVenta.AplicacionWeb/Controllers/NegocioController.cs
using Microsoft.AspNetCore.Mvc;

using AutoMapper;
using Newtonsoft.Json;
using SistemaVenta.AplicacionWeb.Models.ViewModels;
using SistemaVenta.AplicacionWeb.Utilidades.Response;
using SistemaVenta.BBL.Interfaces;
using SistemaVenta.Entity;
using Microsoft.AspNetCore.Authorization;

namespace SistemaVenta.AplicacionWeb.Controllers
{
    [Authorize]
    public class NegocioController : Controller
    {

        private readonly IMapper _mapper;
        private readonly INegocioService _negocioService;

        /// <summary>
        /// Constructor que inicializa una nueva instancia del controlador de negocio.
        /// </summary>
        /// <param name="mapper">Instancia del servicio de mapeo AutoMapper.</param>
        /// <param name="negocioService">Instancia del servicio de negocio.</param>
        public NegocioController(IMapper mapper, INegocioService negocioService)
        {
            _mapper = mapper;
            _negocioService = negocioService;
        }

        /// <summary>
        /// Acción que devuelve la vista principal de la gestión de negocio.
        /// </summary>
        /// <returns>Vista principal de la gestión de negocio.</returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Acción HTTP GET que obtiene la información del negocio y devuelve una respuesta HTTP 200 con el resultado.
        /// </summary>
        /// <returns>Respuesta HTTP 200 con un objeto GenericResponse que contiene la información del negocio.</returns>
        [HttpGet]
        public async Task<IActionResult> Obtener()
        {
            GenericResponse<VMNegocio> genericResponse = new GenericResponse<VMNegocio>();
            try
            {
                VMNegocio vmNegiocio = _mapper.Map<VMNegocio>(await _negocioService.Obtener());
                genericResponse.Estado = true;
                genericResponse.Objeto = vmNegiocio;
            }
            catch (Exception ex)
            {
                genericResponse.Estado = false;
                genericResponse.Mensaje = ex.Message;
                throw;
            }
            return StatusCode(StatusCodes.Status200OK, genericResponse);
        }

        /// <summary>
        /// Acción HTTP POST que guarda los cambios en la información del negocio y devuelve una respuesta HTTP 200 con el resultado.
        /// </summary>
        /// <param name="logo">Instancia de IFormFile que representa el logo del negocio.</param>
        /// <param name="modelo">Cadena JSON que representa el modelo de vista del negocio.</param>
        /// <returns>Respuesta HTTP 200 con un objeto GenericResponse que indica el resultado de la operación.</returns>
        [HttpPost]
        public async Task<IActionResult> GuardarCambios([FromForm]IFormFile logo, [FromForm] string modelo)
        {
            GenericResponse<VMNegocio> genericResponse = new GenericResponse<VMNegocio>();
            try
            {
                VMNegocio vmNegiocio = JsonConvert.DeserializeObject<VMNegocio>(modelo);
                string nombreLogo = "";
                Stream LogoStream = null;

                if(logo != null)
                {
                    string nombreCodificado = Guid.NewGuid().ToString("N");
                    string extension = Path.GetExtension(logo.FileName);
                    nombreLogo = string.Concat(nombreCodificado, extension);
                    LogoStream = logo.OpenReadStream();

                }

                Negocio negiocioEditado = await _negocioService.GuardarCambios(_mapper.Map<Negocio>(vmNegiocio), LogoStream, nombreLogo);

                vmNegiocio = _mapper.Map<VMNegocio>(negiocioEditado);

                genericResponse.Estado = true;
                genericResponse.Objeto = vmNegiocio;
            }
            catch (Exception ex)
            {
                genericResponse.Estado = false;
                genericResponse.Mensaje = ex.Message;
                throw;
            }
            return StatusCode(StatusCodes.Status200OK, genericResponse);
        }
    }
}

SistemaVenta.AplicacionWeb/Controllers/ReporteController.cs
using Microsoft.AspNetCore.Mvc;

using AutoMapper;
using SistemaVenta.AplicacionWeb.Models.ViewModels;
using SistemaVenta.BBL.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace SistemaVenta.AplicacionWeb.Controllers
{
    [Authorize]
    public class ReporteController : Controller
    {

        private readonly IMapper _mapper;
        private readonly IVentaService _ventaService;

        /// <summary>
        /// Constructor que inicializa una nueva instancia del controlador de reportes de ventas.
        /// </summary>
        public ReporteController(IMapper mapper, IVentaService ventaService)
        {
            _mapper = mapper;
            _ventaService = ventaService;
        }

        /// <summary>
        /// Acción que devuelve la vista principal de los reportes.
        /// </summary>
        /// <returns>Vista principal de los reportes.</returns>
        public IActionResult Index()
        {
            return View();
        }

        
        /// <summary>
        /// Acción HTTP GET que obtiene un reporte de ventas según las fechas proporcionadas.
        /// </summary>
        /// <param name="fechaInicio">Fecha de inicio del periodo del reporte.</param>
        /// <param name="fechaFin">Fecha de fin del periodo del reporte.</param>
        /// <returns>Respuesta HTTP 200 con un JSON que contiene los datos del reporte de ventas.</returns>
        [HttpGet]
        public async Task<IActionResult> ReporteVenta(string fechaInicio, string fechaFin)
        {
            List<VMReporteVenta> vmLista = _mapper.Map<List<VMReporteVenta>>(await _ventaService.Reporte(fechaInicio, fechaFin));
            return StatusCode(StatusCodes.Status200OK, new { data = vmLista });

        }
    }
}

SistemaVenta.AplicacionWeb/Controllers/VentaController.cs
using Microsoft.AspNetCore.Mvc;

using AutoMapper;
using SistemaVenta.AplicacionWeb.Models.ViewModels;
using SistemaVenta.AplicacionWeb.Utilidades.Response;
using SistemaVenta.BBL.Interfaces;
using SistemaVenta.Entity;

using DinkToPdf;
using DinkToPdf.Contracts;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace SistemaVenta.AplicacionWeb.Controllers
{
    [Authorize]
    public class VentaController : Controller
    {

        private readonly ITipoDocumentoVentaService _tipoDocumentoVentaService;
        private readonly IVentaService _ventaService;
        private readonly IMapper _mapper;
        private readonly IConverter _converter;

        /// <summary>
        /// Constructor que inicializa una nueva instancia del controlador de ventas.
        /// </summary>
        /// <param name="tipoDocumentoVentaService">Servicio de tipos de documento de venta.</param>
        /// <param name="ventaService">Servicio de ventas.</param>
        /// <param name="mapper">Instancia de IMapper utilizada para mapear entre modelos y entidades.</param>
        /// <param name="converter">Instancia de IConverter utilizada para convertir HTML a PDF.</param>
        public VentaController(ITipoDocumentoVentaService tipoDocumentoVentaService, IVentaService ventaService, IMapper mapper, IConverter converter)
        {
            _tipoDocumentoVentaService = tipoDocumentoVentaService;
            _ventaService = ventaService;   
            _mapper = mapper;
            _converter = converter;
        }


        /// <summary>
        /// Acción HTTP GET que devuelve la vista para realizar una nueva venta.
        /// </summary>
        /// <returns>Vista para realizar una nueva venta.</returns>
        public IActionResult NuevaVenta()
        {
            return View();
        }
        /// <summary>
        /// Acción HTTP GET que devuelve la vista para visualizar el historial de ventas.
        /// </summary>
        /// <returns>Vista para visualizar el historial de ventas.</returns>
        public IActionResult HistorialVenta()
        {
            return View();
        }

        /// <summary>
        /// Acción HTTP GET que obtiene la lista de tipos de documento de venta.
        /// </summary>
        /// <returns>Respuesta HTTP 200 con la lista de tipos de documento de venta.</returns>
        [HttpGet]
        public async Task<IActionResult> ListaTipoDocumentoVenta()
        {
            List<VMTipoDocumentoVenta> vmTipoDocumento = _mapper.Map<List<VMTipoDocumentoVenta>>(await _tipoDocumentoVentaService.Lista());
            return StatusCode(StatusCodes.Status200OK, vmTipoDocumento);
        }

        /// <summary>
        /// Acción HTTP GET que obtiene la lista de productos según una cadena de búsqueda.
        /// </summary>
        /// <param name="busqueda">Cadena de búsqueda para filtrar los productos.</param>
        /// <returns>Respuesta HTTP 200 con la lista de productos filtrada.</returns>
        [HttpGet]
        public async Task<IActionResult> ObtenerProductos(string busqueda)
        {
            List<VMProducto> vmListaProductos = _mapper.Map<List<VMProducto>>(await _ventaService.ObtenerProductos(busqueda));
            return StatusCode(StatusCodes.Status200OK, vmListaProductos);
        }

        /// <summary>
        /// Acción HTTP POST que registra una nueva venta.
        /// </summary>
        /// <param name="modelo">Datos de la venta en formato JSON.</param>
        /// <returns>Respuesta HTTP 200 con un objeto GenericResponse que contiene la venta registrada.</returns>
        [HttpPost]
        public async Task<IActionResult> RegistrarVenta([FromBody] VMVenta modelo)
        {
            GenericResponse<VMVenta> genericResponse = new GenericResponse<VMVenta>();
            try
            {
                ClaimsPrincipal claimUser = HttpContext.User;
                string idUsuario = claimUser.Claims
                    .Where(c => c.Type == ClaimTypes.NameIdentifier) //ClaimTypes.NameIdentifier viene de accesoController, allí a NameIdentifier se le asigna el id del usario
                    .Select(c => c.Value)
                    .FirstOrDefault();


                modelo.IdUsuario = int.Parse(idUsuario);

                Venta ventaCreada = await _ventaService.Registrar(_mapper.Map<Venta>(modelo));
                modelo = _mapper.Map<VMVenta>(ventaCreada);

                genericResponse.Estado = true;
                genericResponse.Objeto = modelo;
            } catch(Exception ex) {
                genericResponse.Estado = false;
                genericResponse.Mensaje = ex.Message;
                Console.WriteLine(ex.ToString());
            }
            return StatusCode(StatusCodes.Status200OK, genericResponse);
        }

        /// <summary>
        /// Acción HTTP GET que obtiene el historial de ventas según el número de venta y un rango de fechas.
        /// </summary>
        /// <param name="numeroVenta">Número de la venta a filtrar.</param>
        /// <param name="fechaInicio">Fecha de inicio del rango de fechas.</param>
        /// <param name="fechaFin">Fecha de fin del rango de fechas.</param>
        /// <returns>Respuesta HTTP 200 con el historial de ventas filtrado.</returns>
        [HttpGet]
        public async Task<IActionResult> Historial(string numeroVenta, string fechaInicio, string fechaFin)
        {
            List<VMVenta> vmHistorialVentas = _mapper.Map<List<VMVenta>>(await _ventaService.Historial(numeroVenta, fechaInicio, fechaFin));
            return StatusCode(StatusCodes.Status200OK, vmHistorialVentas);
        }

        /// <summary>
        /// Acción HTTP GET que genera y muestra un archivo PDF de una venta específica.
        /// </summary>
        /// <param name="numeroVenta">Número de la venta para generar el PDF.</param>
        /// <returns>Archivo PDF de la venta.</returns>
        public IActionResult MostrarPDFVenta(string numeroVenta)
        {
            string urlPlantillaVista = $"{this.Request.Scheme}://{this.Request.Host}/Plantilla/PDFVenta?numeroVenta={numeroVenta}";

            var pdf = new HtmlToPdfDocument()
            {
                GlobalSettings = new GlobalSettings()
                {
                    PaperSize = PaperKind.A4,
                    Orientation = Orientation.Portrait,

                },
                Objects =
                {
                    new ObjectSettings()
                    {
                        Page = urlPlantillaVista
                    }
                }
            };
            var archivoPDF = _converter.Convert(pdf);
            return File(archivoPDF, "application/pdf");
        }

    }
}

SistemaVenta.AplicacionWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>StockHub - @ViewData["Title"]</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet">
    <link href="~/vendor/sweetalert/sweetalert.css" rel="stylesheet">
    <link href="~/css/Dark_Mode.css" rel="stylesheet"/>
    @await RenderSectionAsync("Estilos", required: false)
</head>
<body id="page-top">
    <!--
        @*@Url.Action("Index", "DashBoard")*@
        Index == metodo 
        DashBoard == Controlador
    -->
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Info de la App -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon d-flex align-items-center">
                    <img src="~/img/stockhub - logo.png" alt="Logo de StockHub" style="width: 4rem; height: 4rem;" />
                </div>
                <div class="sidebar-brand-text mx-3">StockHub</div>
            </a>


            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "DashBoard")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Nav Item - Administración Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAdministracion">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Administración</span>
                </a>
                <div id="collapseAdministracion" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index", "Usuario")">Usuarios</a>
                        <a class="collapse-item" href="@Url.Action("Index", "Negocio")">Negocio</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Inventario Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseInventario">
                    <i class="fas fa-fw fa-clipboard-list"></i>
                    <span>Inventario</span>
                </a>
                <div id="collapseInventario" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index", "Categoria")">Categorias</a>
                        <a class="collapse-item" href="@Url.Action("Index", "Producto")">Productos</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Venta Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseVenta">
                    <i class="fas fa-fw fa-tags"></i>
                    <span>Ventas</span>
                </a>
                <div id="collapseVenta" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("NuevaVenta","Venta")">Nueva Venta</a>
                        <a class="collapse-item" href="@Url.Action("HistorialVenta","Venta")">Historial Venta</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Reportes Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseReportes">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Reportes</span>
                </a>
                <div id="collapseReportes" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index", "Reporte")">Reporte de Ventas</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Chat Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Chat")">
                    <i class="fas fa-fw fa-envelope"></i>
                    <span>Chat</span>
                </a>
            </li>


            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>
                        <!-- Nav Item - Dark Mode Toggle -->
                        <li class="nav-item">
                            <a class="nav-link" href="#" id="darkModeToggle">
                                <i class="fas fa-sun fa-fw"></i> <!-- Utilizo fa-sun como símbolo del modo claro -->
                            </a>
                        </li>


                        @await Component.InvokeAsync("MenuUsuario");

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="row">
                        <div class="col-lg-6 mx-auto text-center">
                            <div class="copyright text-center my-auto">
                                <span>Copyright &copy; StockHub 2023</span>
                            </div>
                            <div class="social-icons mt-3">
                                <a href="https://www.facebook.com/andresrodpaz/" target="_blank" class="btn btn-dark btn-circle mx-1">
                                    <i class="fab fa-facebook-f"></i>
                                </a>
                                <a href="https://www.instagram.com/andresrodpaz/" target="_blank" class="btn btn-dark btn-circle mx-1">
                                    <i class="fab fa-instagram"></i>
                                </a>
                                <a href="https://www.linkedin.com/in/andresrodpaz" target="_blank" class="btn btn-dark btn-circle mx-1">
                                    <i class="fab fa-linkedin-in"></i>
                                </a>
                                <a href="https://github.com/andresrodpaz" target="_blank" class="btn btn-dark btn-circle mx-1">
                                    <i class="fab fa-github"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>

            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!--FontAwesome-->
    <script src="https://kit.fontawesome.com/8098a88d9a.js" crossorigin="anonymous"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script src="~/vendor/sweetalert/sweetalert.js"></script>
    <script src="~/vendor/loadingoverlay/loadingoverlay.min.js"></script>

    <script src="~/js/Dark_Mode.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>